version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: registration-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tahar
      POSTGRES_DB: registration_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: registration-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./app:/app